model_params:
  fp16: false       # general flag
  model: lstmbased   # model from NETWORKS to use
  img_encoder:
    sequence_length: 64
    input_size: 64
    hidden_size: 128
    num_layers: 2
    num_classes: 340
    num_embeddings: 300
    embedding_dim: 10
    use_cnn: True
    use_embedding: True
    use_lstm_image: True
    use_lstm_stroke: True

args:
  workers: 0
  model_dir: "quickdraw"
  baselogdir: "./logs/quickdraw"

stages:

  state_params:
    main_metric: map03
    minimize_metric: False

  criterion_params:
    criterion: CrossEntropyLoss

  data_params:
    train_split: "/media/ngxbac/Bac/competition/kaggle/competition_data/quickdraw/data/split/train_5/"
    train_token: "/media/ngxbac/Bac/competition/kaggle/competition_data/quickdraw/data/split/train_5_token/"

    valid_split: "/media/ngxbac/Bac/competition/kaggle/competition_data/quickdraw/data/split/valid_5/"
    valid_token: "/media/ngxbac/Bac/competition/kaggle/competition_data/quickdraw/data/split/valid_5_token/"

  callbacks_params:
#    emb_l2_reg: -1
#    precision_args: [3]
    map_args: [3]
#    main_metric: map03
#    minimize_metric: false

  # train head
  stage1:
    args:
      epochs: 6
      batch_size: 128

    optimizer_params:
      optimizer: Adam
      lr: 0.0001
      weight_decay: 0.0001

    scheduler_params:
      scheduler: StepLR
      step_size: 4
      gamma: 0.1

    data_params:
      reload_loaders: true
